window.DZ_COURSES = [
['vente','🛒','Vente en ligne','Lancer une activité e-commerce en Algérie','7 modules • 42 leçons','formation-vente.html'],
['freelance','💻','Freelancing','Transformer une compétence en service vendable','8 modules • 48 leçons','formation-freelance.html'],
['ia','🤖','IA pratique','Utiliser l’IA pour apprendre, créer et travailler','7 modules • 35 leçons','formation-ia.html'],
['contenu','🎬','Création de contenu','Créer Reels, vidéos, visuels et calendriers','7 modules • 40 leçons','formation-contenu.html'],
['marketing','📣','Marketing digital','Attirer une audience et mesurer les résultats','8 modules • 45 leçons','formation-marketing.html'],
['site','🌐','Création de sites','Créer et publier un site professionnel','8 modules • 44 leçons','formation-site.html'],
['canva','🎨','Canva & design','Créer des visuels professionnels sans être graphiste','6 modules • 32 leçons','formation-canva.html'],
['video','🎥','Montage vidéo','Monter des vidéos courtes pour les réseaux','6 modules • 34 leçons','formation-video.html'],
['copy','✍️','Copywriting','Écrire des textes qui présentent clairement une offre','6 modules • 30 leçons','formation-copywriting.html'],
['social','📱','Réseaux sociaux','Construire une présence régulière et utile','6 modules • 36 leçons','formation-social.html'],
['ads','🎯','Publicité Meta & TikTok','Comprendre campagnes, audiences et suivi','7 modules • 38 leçons','formation-publicite.html'],
['seo','🔎','SEO','Améliorer la visibilité d’un site sur Google','6 modules • 34 leçons','formation-seo.html'],
['digital-products','📦','Produits digitaux','Créer guides, templates et ressources numériques','6 modules • 31 leçons','formation-produits.html'],
['marketplace','🛍️','Marketplace','Présenter produits, catalogue et commandes','6 modules • 30 leçons','formation-marketplaces.html'],
['remote','🏠','Travail à distance','Organiser sa recherche d’opportunités en ligne','6 modules • 30 leçons','formation-remote.html'],
['data','📊','Excel & reporting','Tableaux, KPI, analyse et reporting','7 modules • 42 leçons','formation-data.html'],
['nocode','⚙️','Automatisation no-code','Automatiser des tâches répétitives','6 modules • 32 leçons','formation-no-code.html'],
['branding','⭐','Personal branding','Présenter son expertise de façon cohérente','6 modules • 30 leçons','formation-personal-branding.html'],
['email','📧','Email marketing','Construire une liste et des campagnes utiles','6 modules • 30 leçons','formation-email.html'],
['service','🤝','Créer une offre de service','Définir, tarifer et vendre une prestation','6 modules • 31 leçons','formation-service.html'],
['productivity','⏱️','Productivité digitale','S’organiser, prioriser et travailler avec méthode','5 modules • 25 leçons','methodologie.html'],
['portfolio','🗂️','CV & Portfolio','Créer des preuves de compétences','5 modules • 25 leçons','cv-portfolio.html'],
['client','📞','Prospection client','Trouver et contacter des prospects proprement','6 modules • 30 leçons','projets.html'],
['finance','💰','Gestion d’une activité digitale','Suivre prix, coûts, marge et objectifs','5 modules • 25 leçons','formation-data.html'],
['security','🔐','Sécurité numérique','Protéger comptes, données et paiements','5 modules • 25 leçons','ressources.html']
];
